spring:
  datasource:
    url: jdbc:h2:mem:${DB_DATABASE};DB_CLOSE_ON_EXIT=TRUE
    name: ${DB_DATABASE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
